version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Set this to the folder with your package.json
    schedule:
      interval: "weekly" # Options: "daily", "weekly", "monthly"
    commit-message:
      prefix: "chore"

    # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
