name: Build and publish a Docker image to ghcr.io
on:
  # publish on pushes to the main branch (image tagged as "latest")
  push:
    branches:
      - main

jobs:
  docker_publish:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - name: build and push
        run: |
          docker login --username fasonju --password ${{secrets.GH_PAT}} ghcr.io
          docker build . --tag ghcr.io/fasonju/portfolio:latest
          docker push  ghcr.io/fasonju/portfolio:latest
